/usr/bin/id: cannot find name for group ID 2000
/usr/bin/id: cannot find name for user ID 2019
Traceback (most recent call last):
  File "/mnt/beegfs/lcesarini/ge-distance/src/distance/./create_ensemble.py", line 193, in <module>
    with open(f'/src/distance/out/UL_italy_poly_assigned_{n_grid}.json', 'r', encoding='utf-8') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/src/distance/out/UL_italy_poly_assigned_95.json'
srun: error: cn04: task 0: Exited with exit code 1
